version: "3.8"

services:
    mercury-chat:
        container_name: mercury-chat
        image: truongnhan0311/debian:mercury-chat
        ports:
            - "8088:8000"
        restart: always
        depends_on:
            - chat-mysql
            - chat-redis
            - chat-mail
        volumes:
            - .:/var/www/:delegated
            - ./Docker/run.sh:/run.sh
    chat-redis:
        container_name: chat-redis
        image: redis:7.0-alpine
        restart: always
        volumes:
            - ./Docker/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis-data:/data
        environment:
            - REDIS_REPLICATION_MODE=master
    chat-mail:
        container_name: chat-mail
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - "1027:1025"
            - "8027:8025"
    chat-mysql:
        container_name: chat-mysql
        image: mariadb:10.11
        ports:
            - 3309:3306
        environment:
            - TZ=Asia/Tokyo
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ecomnist-api
            - MYSQL_USER=ecomnist
            - MYSQL_PASSWORD=Ecomnist@2023!
        volumes:
            - ./chat-mysql:/var/lib/mysql:cached
        restart: always

    chat-mercure-server:
        image: dunglas/mercure
        restart: unless-stopped
        container_name: chat-mercure-server
        ports:
            - "3000:3000"
        environment:
            SERVER_NAME: ':3000'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://127.0.0.1:8000
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config
volumes:
    chat-mysql:
    redis-data:
    mercure_data:
    mercure_config: